# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "nginx-vts-exporter-${version}";
  version = "0.10.3";

  goPackagePath = "github.com/hnlq715/nginx-vts-exporter";

  src = fetchFromGitHub {
    rev = "v${version}";
    owner = "hnlq715";
    repo = "nginx-vts-exporter";
    sha256 = "05zf6s1jsbsni51ghnllin2d3bj16q3dy0y2xvb8l5f8rkglxkh4";
  };

  meta = with stdenv.lib; {
    description = "Metrics relay from nginx-vts stats to Prometheus";
    homepage = https://github.com/hnlq715/nginx-vts-exporter;
    license = licenses.mit;
    maintainers = with maintainers; [ disassembler ];
    platforms = platforms.unix;
  };
}
